### ISSUE TITLE
ModuleNotFoundError: No module named 'sng_parser.audio

### ISSUE THREAD

**Issue by cd-cd-cd** [navervision/lincir#18]
Thank you very much for your open-source code! I encountered a 'ModuleNotFoundError: No module named 'sng_parser.audio'' issue during the reproduction process. Could you please let me know which version of 'sng_parser' you are using? I would appreciate your guidance on how to resolve this issue.
`Traceback (most recent call last):
  File "/amax/home/chendian/lincir-master/train_phi.py", line 21, in <module>
    from loader import build_loader, CIRRDataset
  File "/amax/home/chendian/lincir-master/loader.py", line 20, in <module>
    import sng_parser
  File "/amax/home/chendian/miniconda3/envs/lincir/lib/python3.10/site-packages/sng_parser/__init__.py", line 3, in <module>
    from .encode import encode_sng
  File "/amax/home/chendian/miniconda3/envs/lincir/lib/python3.10/site-packages/sng_parser/encode.py", line 26, in <module>
    from .audio import parllel_transcode_opus, eval_audio_futures
ModuleNotFoundError: No module named 'sng_parser.audio'
Traceback (most recent call last):
  File "/amax/home/chendian/lincir-master/train_phi.py", line 21, in <module>
    from loader import build_loader, CIRRDataset
  File "/amax/home/chendian/lincir-master/loader.py", line 20, in <module>
    import sng_parser
  File "/amax/home/chendian/miniconda3/envs/lincir/lib/python3.10/site-packages/sng_parser/__init__.py", line 3, in <module>
    from .encode import encode_sng
  File "/amax/home/chendian/miniconda3/envs/lincir/lib/python3.10/site-packages/sng_parser/encode.py", line 26, in <module>
    from .audio import parllel_transcode_opus, eval_audio_futures
ModuleNotFoundError: No module named 'sng_parser.audio'`

**Comment by geonm** [comment]
`sng_parser` is a legacy module which we used for some experiments.

I removed it with the hotfix https://github.com/navervision/lincir/commit/d95726469a2ab849e4fe7f51aced922b0c71ee8b.

Please update your LinCIR code from the latest master branch.
